export const DEFAULT_FIELDS_VALUES = {
  text1: undefined,
  text2: undefined,
  text3: undefined,
  long1: undefined,
  long2: undefined,
  long3: undefined,
  num1: undefined,
  num2: undefined,
  num3: undefined,
  link1: undefined,
  link2: undefined,
  link3: undefined,
  bool1: undefined,
  bool2: undefined,
  bool3: undefined,
};
