export const APP_ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  INVENTORIES: '/inventories',
  INVENTORY_VIEW: '/inventory/:inventoryId',
  INVENTORY_SETTINGS: '/inventory/:inventoryId/settings',
  INVENTORY_ITEMS: '/inventory/:inventoryId/items',
  ITEM_VIEW: '/item/:itemId',
  ITEM_CREATE: '/inventory/:inventoryId/items/new',
  SEARCH: '/search',
  PROFILE: '/profile/:userId',
  ADMIN_USERS: '/admin/users',
  CREATE_INVENTORY: '/inventory/new',
  MY_INVENTORIES: '/inventories/my',
} as const;
